#!/usr/bin/env pwsh
<#
.SYNOPSIS
Mirrors canonical agent and skill libraries into the .claude/ host directory that
both Claude Code and GitHub Copilot read.

.DESCRIPTION
The canonical source of truth is per-language directories at the repo root, each
containing agents/ and/or skills/ subdirectories — for example, Python/agents/ and
Python/skills/. Add more languages as sibling directories (Go/, JavaScript/, ...).

Both hosts discover agents and skills under .claude/:
  - Claude Code reads .claude/agents and .claude/skills.
  - GitHub Copilot also discovers custom agents under .claude/agents and skills
    under .claude/skills (in addition to .github/ and .agents/).

So a single generated .claude/ directory serves both — there is no separate
.github/ copy. The .claude/ agents and skills are build artifacts: they are
gitignored and regenerated by this script.

Because both hosts expect a flat list of agents and a flat list of skill folders,
this script aggregates the selected language sources into a single flat .claude/
destination. Agent files keep their bare names (no language prefix), so sync one
language at a time — pass -Languages to scope the run — to avoid cross-language
filename collisions in the shared destination.

Agents declare tools in the PascalCase form that both hosts read natively
(Read, Edit, Write, Grep, Glob, Bash, WebSearch, WebFetch, Task, TodoWrite) —
Claude Code reads these directly and GitHub Copilot recognizes them as its
documented tool aliases. Agent and skill files are copied verbatim; no
frontmatter rewriting is performed.

.PARAMETER Languages
Limit the sync to a subset of source languages. Default: every top-level
directory containing an agents/ or skills/ subfolder.

.PARAMETER Clean
Wipe destination directories before syncing.

.EXAMPLE
pwsh scripts/sync-to-host.ps1

.EXAMPLE
pwsh scripts/sync-to-host.ps1 -Languages Python -Clean
#>
[CmdletBinding()]
param(
    [string[]] $Languages,

    [switch] $Clean
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')

# Directories at repo root that are never source languages.
$ExcludedRootDirs = @('.git', '.github', '.claude', '.vscode', '.idea', 'scripts', 'node_modules')

function Get-LanguageDirs {
    $candidates = Get-ChildItem -Path $RepoRoot -Directory |
        Where-Object { $_.Name -notin $ExcludedRootDirs }

    if ($Languages) {
        $candidates = $candidates | Where-Object { $_.Name -in $Languages }
        if (-not $candidates) {
            throw "No matching language directories found for: $($Languages -join ', ')"
        }
    }

    # Keep only directories that actually contain agents/ or skills/.
    $candidates | Where-Object {
        (Test-Path (Join-Path $_.FullName 'agents')) -or
        (Test-Path (Join-Path $_.FullName 'skills'))
    }
}

# Single host destination read by both Claude Code and GitHub Copilot.
$AgentsDest = Join-Path $RepoRoot '.claude/agents'
$SkillsDest = Join-Path $RepoRoot '.claude/skills'

function Ensure-Dir {
    param([string] $Path)
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Clear-Dir {
    param([string] $Path)
    if (Test-Path $Path) {
        Write-Host "  cleaning $Path"
        Remove-Item $Path -Recurse -Force
    }
    Ensure-Dir $Path
}

$languageDirs = @(Get-LanguageDirs)
if (-not $languageDirs) {
    throw "No source language directories with agents/ or skills/ found under $RepoRoot."
}

Write-Host "Source languages: $($languageDirs.Name -join ', ')"
Write-Host ""
Write-Host "→ syncing to .claude/ (read by Claude Code and GitHub Copilot)"

if ($Clean) {
    Clear-Dir $AgentsDest
    Clear-Dir $SkillsDest
} else {
    Ensure-Dir $AgentsDest
    Ensure-Dir $SkillsDest
}

foreach ($lang in $languageDirs) {
    $srcAgents = Join-Path $lang.FullName 'agents'
    $srcSkills = Join-Path $lang.FullName 'skills'

    if (Test-Path $srcAgents) {
        Write-Host "  $($lang.Name)/agents/  →  $AgentsDest"
        foreach ($agentFile in Get-ChildItem -Path $srcAgents -Filter '*.md' -File) {
            $dest = Join-Path $AgentsDest $agentFile.Name
            Copy-Item -Path $agentFile.FullName -Destination $dest -Force
        }
    }

    if (Test-Path $srcSkills) {
        Write-Host "  $($lang.Name)/skills/  →  $SkillsDest"
        Get-ChildItem -Path $srcSkills -Directory | ForEach-Object {
            $destSkill = Join-Path $SkillsDest $_.Name
            Ensure-Dir $destSkill
            Copy-Item -Path (Join-Path $_.FullName '*') -Destination $destSkill -Recurse -Force
        }
    }
}

Write-Host ""
Write-Host "Done. Canonical source: <Language>/agents/, <Language>/skills/"
Write-Host "Edit canonical files; re-run this script to update .claude/."
