#!/usr/bin/env bash
# Mirrors canonical agent and skill libraries into the .claude/ host directory
# that both Claude Code and GitHub Copilot read.
#
# The canonical source of truth is per-language directories at the repo root,
# each containing agents/ and/or skills/ subdirectories — for example,
# Python/agents/ and Python/skills/. Add more languages as sibling directories.
#
# Both hosts discover agents and skills under .claude/:
#   - Claude Code reads .claude/agents and .claude/skills.
#   - GitHub Copilot also discovers custom agents under .claude/agents and skills
#     under .claude/skills (in addition to .github/ and .agents/).
# So a single generated .claude/ directory serves both — there is no separate
# .github/ copy. The .claude/ agents and skills are build artifacts: gitignored
# and regenerated by this script.
#
# Because both hosts expect a flat list of agents and a flat list of skill
# folders, this script aggregates the selected language sources into a single
# flat .claude/ destination. Agent files keep their bare names (no language
# prefix), so sync one language at a time — pass --lang to scope the run — to
# avoid cross-language filename collisions in the shared destination.
#
# Agents declare tools in the PascalCase form that both hosts read natively
# (Read, Edit, Write, Grep, Glob, Bash, WebSearch, WebFetch, Task, TodoWrite) —
# Claude Code reads these directly and GitHub Copilot recognizes them as its
# documented tool aliases. Agent and skill files are copied verbatim; no
# frontmatter rewriting is performed.
#
# Usage:
#   ./scripts/sync-to-host.sh                 # sync all languages
#   ./scripts/sync-to-host.sh --lang Python   # one language only
#   ./scripts/sync-to-host.sh --clean         # wipe destination first

set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$( cd -- "${SCRIPT_DIR}/.." &> /dev/null && pwd )"

EXCLUDED_DIRS=(.git .github .claude .vscode .idea scripts node_modules)

CLEAN=0
LANGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --clean) CLEAN=1; shift ;;
        --lang)
            if [[ -z "${2:-}" ]]; then
                echo "--lang requires a language directory name" >&2; exit 2
            fi
            LANGS+=("$2"); shift 2 ;;
        -h|--help)
            sed -n '2,20p' "$0"; exit 0 ;;
        *)
            echo "Unknown argument: $1" >&2
            echo "Usage: $0 [--lang <name>]... [--clean]" >&2
            exit 2 ;;
    esac
done

is_excluded() {
    local name="$1"
    for excluded in "${EXCLUDED_DIRS[@]}"; do
        [[ "$name" == "$excluded" ]] && return 0
    done
    return 1
}

discover_languages() {
    local -a found=()
    for dir in "${REPO_ROOT}"/*/; do
        [[ -d "$dir" ]] || continue
        local name; name=$(basename "$dir")
        is_excluded "$name" && continue

        # If --lang was passed, filter.
        if [[ ${#LANGS[@]} -gt 0 ]]; then
            local match=0
            for wanted in "${LANGS[@]}"; do
                [[ "$name" == "$wanted" ]] && match=1
            done
            [[ $match -eq 1 ]] || continue
        fi

        # Only include if it has agents/ or skills/.
        if [[ -d "${dir}/agents" || -d "${dir}/skills" ]]; then
            found+=("$name")
        fi
    done
    printf '%s\n' "${found[@]}"
}

mapfile -t LANG_DIRS < <(discover_languages)

if [[ ${#LANG_DIRS[@]} -eq 0 ]]; then
    echo "No source language directories with agents/ or skills/ found under ${REPO_ROOT}" >&2
    exit 1
fi

echo "Source languages: ${LANG_DIRS[*]}"
echo ""

ensure_dir() { mkdir -p "$1"; }
clear_dir()  { [[ -d "$1" ]] && { echo "  cleaning $1"; rm -rf "$1"; }; mkdir -p "$1"; }

# Single host destination read by both Claude Code and GitHub Copilot.
agents_dst="${REPO_ROOT}/.claude/agents"
skills_dst="${REPO_ROOT}/.claude/skills"

echo "→ syncing to .claude/ (read by Claude Code and GitHub Copilot)"

if [[ $CLEAN -eq 1 ]]; then
    clear_dir "$agents_dst"
    clear_dir "$skills_dst"
else
    ensure_dir "$agents_dst"
    ensure_dir "$skills_dst"
fi

for lang in "${LANG_DIRS[@]}"; do
    src_agents="${REPO_ROOT}/${lang}/agents"
    src_skills="${REPO_ROOT}/${lang}/skills"

    if [[ -d "$src_agents" ]]; then
        echo "  ${lang}/agents/  →  ${agents_dst}"
        for agent_file in "${src_agents}"/*.md; do
            [[ -f "$agent_file" ]] || continue
            dest="${agents_dst}/$(basename "$agent_file")"
            cp -f "$agent_file" "$dest"
        done
    fi

    if [[ -d "$src_skills" ]]; then
        echo "  ${lang}/skills/  →  ${skills_dst}"
        for skill_dir in "${src_skills}"/*/; do
            [[ -d "$skill_dir" ]] || continue
            name=$(basename "$skill_dir")
            mkdir -p "${skills_dst}/${name}"
            cp -rf "${skill_dir}/." "${skills_dst}/${name}/"
        done
    fi
done

echo ""
echo "Done. Canonical source: <Language>/agents/, <Language>/skills/"
echo "Edit canonical files; re-run this script to update .claude/."
